repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length=79"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v6.0.0
    hooks:
      - id: flake8
        args: ["--max-complexity=30"]
