name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (with dev)
        run: |
          poetry config virtualenvs.create false --local
          poetry install --with dev

      - name: Run ruff (format & lint)
        run: |
          poetry run ruff check src tests || true

      - name: Run flake8
        run: |
          poetry run flake8 src tests

      - name: Run pytest
        run: |
          poetry run pytest -q

  docs:
    name: Build & Deploy Docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (with dev)
        run: |
          poetry config virtualenvs.create false --local
          poetry install --with dev

      - name: Build mkdocs site
        run: |
          poetry run mkdocs build -d site

      - name: Deploy to gh-pages (peaceiris)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
