name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (poetry)
        run: |
          poetry config virtualenvs.create false --local
          poetry install --no-interaction --with dev

      - name: Lint with ruff
        run: poetry run ruff check src tests

      - name: Lint with flake8
        run: poetry run flake8 src tests

      - name: Run tests
        run: poetry run pytest -q
